# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('answer', models.CharField(default='Please wait for your question to be answered', max_length=512)),
                ('user', models.CharField(max_length=125)),
            ],
        ),
    ]
