# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guides',
            name='document',
            field=models.FileField(upload_to='media/guides'),
        ),
    ]
