# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 06:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='home',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
