# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160714_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='home',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
