# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='facebook',
            field=models.CharField(blank=True, default='#', max_length=125),
        ),
        migrations.AlterField(
            model_name='member',
            name='github',
            field=models.CharField(blank=True, default='#', max_length=125),
        ),
        migrations.AlterField(
            model_name='member',
            name='linkedin',
            field=models.CharField(blank=True, default='#', max_length=125),
        ),
    ]
