# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 05:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160918_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('netid', models.CharField(max_length=125)),
                ('year', models.CharField(max_length=125)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime(2016, 11, 10, 5, 53, 24, 930446))),
            ],
        ),
    ]
