# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 06:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='challenge',
            field=models.CharField(default=django.utils.timezone.now, max_length=125),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 11, 10, 6, 1, 21, 93536)),
        ),
    ]
