# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-12 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20161110_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='location',
            field=models.CharField(default='Thurston 205', max_length=125),
        ),
        migrations.AlterField(
            model_name='form',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
