# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_auto_20160712_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectures',
            name='document',
            field=models.FileField(upload_to='media/lectures'),
        ),
    ]
