# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writeups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_CTF', models.CharField(max_length=125)),
                ('date_competed', models.CharField(max_length=125)),
                ('place', models.IntegerField()),
                ('out_of', models.IntegerField()),
                ('description', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
