# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writeups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_CTF', models.CharField(max_length=125)),
                ('url_of_CTF', models.URLField()),
                ('date_competed', models.CharField(max_length=125)),
                ('place', models.IntegerField()),
                ('out_of', models.IntegerField()),
                ('description', models.TextField()),
                ('writeup', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
