# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 01:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0002_writeups_url_of_ctf'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeups',
            name='document',
            field=models.FileField(default=datetime.datetime(2016, 7, 13, 1, 0, 34, 866476, tzinfo=utc), upload_to='media/writeups'),
            preserve_default=False,
        ),
    ]
