# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 01:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0003_writeups_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeups',
            name='document',
        ),
        migrations.AddField(
            model_name='writeups',
            name='writeup',
            field=models.TextField(default=datetime.datetime(2016, 7, 13, 1, 10, 55, 414635, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
